# name=input("enter the name")
# prt=open("sravan.txt",'w')
# prt.write(name)
# prt.close()

# name=input("enter the name :")
# prt=open("sravan.txt",'a')
# prt.write(name)
# prt.close()

# name=input("enter the name :")
prt=open("sravan.txt",'r')
res=prt.readline()
print(res)
prt.close()